name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/advice-odds-client:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/advice-odds-client:latest
